### ISSUE TITLE
Empty Response regardless of file presence 

### ISSUE THREAD

**Issue by nromito** [spacer59/cribl-log-collection#1]
I added some log files to `src/main/resources/machine-1` and queried for them (ex. `file_name=wifi`) and received an empty array response. I double checked that it was indeed finding the file by dropping a log statement in the code myself.

**Comment by spacer59** [comment]
Hi Nick, I need a little more context specifically the request uri and log file to check the format of log entries. 

I was unable to reproduce this issue using the following steps,
- Add new file called `wifi.log` to `src/main/resources/machine-1`
- Query logs in `wifi.log` using the following request uri http://localhost:8080/logs?file_name=wifi. Note that since no machines are provided in the request the server will query it's own machines log files, in this case we use port 8080 where machine-1 is running.
- Alternately I tried explicitly including machine-1 in the request. Using this allows you to access any port. eg: http://localhost:8082/logs?file_name=wifi&machines=machine-1
- In both cases I was able to retrieve log entries.

I can potentially see two issues here, 
- The request uri is incorrect, wrong port/machine without machines request parameter
- All log entries in the file are invalid (log format does not match the `timestamp LEVEL body` format)

This PR https://github.com/spacer59/cribl-log-collection/pull/4 logs file path and issues a warning when no log entries can be parsed, for more visibility.

**Comment by nromito** [comment]
> All log entries in the file are invalid (log format does not match the timestamp LEVEL body format)

This is no doubt the reason it failed. This is probably too strong of an assumption to make as logs can come in any form, shape, or size

**Comment by spacer59** [comment]
I am not exactly sure how we will be able to extract the timestamp or log level without knowing the format before hand
eg: if logs are stored in json format we will need to know which keys to reference for extraction

We will also need to know the timestamp format? If date times are encoded in a custom format, I am not sure how we can extract it from the log file even if we assume the log entry starts with a timestamp.

What are your thoughts on this approach?
- log entry always starts with an ISO formatted timestamp

**Comment by spacer59** [comment]
Open to other suggestions here

**Comment by spacer59** [comment]
Also looks like I forgot to commit sample files in the resources directory originally. They should be in the project root now.

**Comment by nromito** [comment]
I think for this project, we can leave out the merging by timestamp across multiple machines just to simplify things a bit. However, if you want, you can default to using `now()` if your heuristics don't match against a timestamp.

Parsing out timestamps in events is a non-trivial problem for sure

**Comment by spacer59** [comment]
Just created this PR https://github.com/spacer59/cribl-log-collection/pull/7 to simplify ReverseLogReader implementation and log format. I was able to query newly added log files with any format.
