### ISSUE TITLE
503 response and large resource usage when querying large log files

### ISSUE THREAD

**Issue by nromito** [spacer59/cribl-log-collection#3]
Attempted to query a 5GB log file and received:
```
nromito-mbp:cribl-log-collection nromito$ http ':8080/logs?file_name=test&machines=machine-1'
HTTP/1.1 503 Service Unavailable
Content-Length: 105
Content-Type: text/plain; charset=UTF-8
Date: Mon, 16 Aug 2021 22:49:01 GMT
Server: akka-http/10.2.6

The server was not able to produce a timely response to your request.
Please try again in a short while!
```

Upon checking `top`, I found that the app was still consuming a ton of resources:
```
46023  java         197.9 01:37.50 89/2   1    268   1133M  0B     159M   46023 43537 running  *0[1]            0.00000 0.00000    501
```

I'd expect to get a valid response of the content of the log file in this case.

**Comment by spacer59** [comment]
I was able to reproduce the same and have identified the edge case causing this. 

When the log file contains log entries in invalid format, `ReverseLogReader` keeps adding to `multiLineBuffer` but there is no check on the maximum number of lines in a log entry. Due to this it scans the entire log file until it reaches the beginning of the file which likely fills up the buffers explaining the high memory usage.

One way to handle this is check the first line (or perhaps even first n lines) of the log file to detect if it is a valid log entry (i.e it starts with an ISO formatted timestamp). If we can determine it is is valid log file we proceed with the reverse scan knowing that we will be able to extract log entries and always max out at n log entries (having validated that n cannot exceed a maximum value).

Note: This is related to a discussion in https://github.com/spacer59/cribl-log-collection/issues/1 regarding log format.

**Comment by spacer59** [comment]
Just created this PR https://github.com/spacer59/cribl-log-collection/pull/7 to simplify log format and ReverseLogReader implementation. This change also ensures only last n log entries are read and a full file scan is avoided which resolves resource consumption and request timeout.
